<?php
/**
 * Created by PhpStorm.
 * file: Gateway.php
 * project: omnipay-heepay
 * User: ChingLi
 * Date: 2016/12/19
 * Time: 16:47
 */

namespace Omnipay\Heepay;

use Omnipay\Common\AbstractGateway;

/**
 * Class Gateway Heepay汇付宝网关
 * @package Omnipay\Heepay
 * @author ChingLi
 */
class Gateway extends AbstractGateway
{
    /**
     * 获取名称
     * @return string
     * @author ChingLi
     */
    public function getName()
    {
        return 'Heepay';
    }

    /**
     * 获取默认参数
     * @return string[]
     * @author ChingLi
     */
    public function getDefaultParameters(){
        return [
            'desc'      => '',
            'key'       => '',
            'deskey'    => '',
            'partner'   => '',      //汇付宝注册的账户数字ID
            'notifyurl' => '',
            'qq'        => '',
            'email'     => '',
            'ext_param' => '',
        ];
    }

    /**
     * 设置key
     * @param $value
     * @return mixed
     * @author ChingLi
     */
    public function setKey($value){
        return $this->setParameter('key',$value);
    }

    /**
     * 设置DesKey
     * @param $value
     * @return mixed
     * @author ChingLi
     */
    public function setDesKey($value){
        return $this->setParameter('deskey',$value);
    }

    /**
     * 设置Partner
     * @param $value
     * @return mixed
     * @author ChingLi
     */
    public function setPartner($value){
        return $this->setParameter('partner',$value);
    }

    /**
     * 设置回调地址
     * @param $value
     * @return mixed
     * @author ChingLi
     */
    public function setNotifyurl($value){
        return $this->setParameter('notifyurl',$value);
    }

    /**
     * 获取key
     * @return mixed
     * @author ChingLi
     */
    public function getKey(){
        return $this->getParameter('key');
    }

    /**
     * 获取DesKey
     * @return mixed
     * @author ChingLi
     */
    public function getDesKey(){
        return $this->getParameter('deskey');
    }

    /**
     * 获取Partner
     * @return mixed
     * @author ChingLi
     */
    public function getPartner(){
        return $this->getParameter('partner');
    }

    /**
     * 获取回调地址
     * @return mixed
     * @author ChingLi
     */
    public function getNotifyurl(){
        return $this->getParameter('notifyurl');
    }

    public function purchase(array $parameters = array()){
        return $this->createRequest('\Omnipay\Heepay\Message\HeepayPurchaseRequest', $parameters);
    }

    public function supportsCompletePurchase()
    {
        return parent::supportsCompletePurchase(); // TODO: Change the autogenerated stub
    }

    /**
     * 异步回调
     * @param array $options 回调数据
     * @return \Omnipay\Common\Message\AbstractRequest
     * @author ChingLi
     */
    public function completePurchase(array $options = array())
    {
        // TODO: Implement completePurchase() method.
        return $this->createRequest('\Omnipay\Heepay\Message\HeepayCompletePurchaseRequest',$options);
    }
}