<?php
/**
 * Created by PhpStorm.
 * file: Gateway.php
 * project: omnipay-heepay
 * User: 李静
 * Date: 2016/12/19
 * Time: 16:47
 */

namespace Omnipay\Heepay;

use Omnipay\Common\AbstractGateway;

/**
 * Class Gateway Heepay汇付宝网关
 * @package Omnipay\Heepay
 * @author 李静
 */
class Gateway extends AbstractGateway{
    public function getName()
    {
        // TODO: Implement getName() method.
        return 'Heepay';
    }
    public function getDefaultParameters()
    {
        // TODO: Change the autogenerated stub
        // 临时数据
        return array(
            'merId' => '',
            'apikey' => '',
            'verifyType' => '1',
            'version' => '3'
        );
    }
    public function getPartnerId()
    {
        return $this->getParameter('partnerId');
    }
    public function setPartnerId($value)
    {
        return $this->setParameter('partnerId',$value);
    }
    public function getApiKey()
    {
        return $this->getParameter('apiKey');
    }
    public function setApiKey($value)
    {
        return $this->setParameter('apiKey',$value);
    }
    public function getNotifyUrl()
    {
        return $this->getParameter('notifuUrl');
    }
    public function setNotifyUrl($value)
    {
        return $this->setParameter('notifuUrl',$value);
    }
    public function purchase(array $options = array())
    {
        // TODO: Implement purchase() method.
        return $this->createRequest('\Omnipay\Heepay\Message\HeepayPurchaseRequest',$options);
    }
    public function completePurchase(array $options = array())
    {
        // TODO: Implement completePurchase() method.
        return $this->createRequest('\Omnipay\Heepay\Message\HeepayCompletePurchaseRequest',$options);
    }
}